development:  
  adapter: postgresql
  encoding: unicode
  database: demo_app
  pool: 5
  username: ericjohniglesia@gmail.com
  password: maximumspider

test:  
  adapter: postgresql
  encoding: unicode
  database: demo_app
  pool: 5
  username: ericjohniglesia@gmail.com
  password: maximumspider